### ISSUE TITLE
Doesn't work with KDE5 / Plasma

### ISSUE THREAD

**Issue by djtm** [graboluk/stiko#2]
There are zero error messages in syncthing or stiko, except when I try to close it:

``` shell
^CTraceback (most recent call last):
  File "./stiko.py", line 120, in <lambda>
    GObject.idle_add(lambda :self.gui.update_icon(self)) 
KeyboardInterrupt
```

I'm on Ubuntu 15.10 amd64 with syncthing 0.12.21 and stiko-git.

**Comment by graboluk** [comment]
Thanks for the report. Just to make sure I understand corectly - when you
run stiko.py from command line there are no reports about errors, but
there's also no icon in your taskbar?

2016-04-06 14:44 GMT+01:00 djtm notifications@github.com:

**Comment by djtm** [comment]
Precisely.

**Comment by graboluk** [comment]
1)What taskbar do you use? I use tint2. Wold you be able to check if it
works with tint2?

2) Could you start and stop stiko say three times (no need to restart
syncthing) and let me know if the message is exactly the same?

2016-04-06 15:10 GMT+01:00 djtm notifications@github.com:

**Comment by djtm** [comment]
The error is consistent. Actually I can't close with ctrl c, which shows the error each time, but need to kill manually. 

 I use kde plasma. I'll check tint later.

**Comment by graboluk** [comment]
I googled around and it seems KDE has some issues with the gtk.statusicon,
see for example here:
http://forums.fedoraforum.org/showthread.php?t=307529
(a minimal python script is given there which "used to work" but no longer
works in plasma.)

Apparently dropbox icon also doesn't show in Plasma (as of March 2015):
https://www.dropboxforum.com/hc/en-us/community/posts/201908279-Systray-icon-not-showing-in-KDE-Plasma-5-2
At the end of this thread a user offers a solution, which maybe would make
the stiko icon appear as well?

In any case it would be really helpful if you could try a systray which is
compatible with the freedesktop specificaiton (for example tint2).

I do want to be clear though - if the issue is that KDE doesn't allow using
gtk.statusicon then I won't be able to do much about it (I'm not a KDE user
and currently don't have enough spare time to learn about intricacies of
KDE systray...)

2016-04-06 15:32 GMT+01:00 djtm notifications@github.com:

**Comment by djtm** [comment]
Confirmed to work with tint2. Would be nice to be able to exit with Ctrl-C, still. 

I'll try again with KDE 5.5, which should contain a fix for this. Dropbox works for me. xembed seems deprecated, however.

**Comment by djtm** [comment]
Closing as #wontfix.
